### ISSUE TITLE
Does this support portable VSCode?

### ISSUE THREAD

**Issue by jjw24** [taooceros/Flow.Plugin.VSCodeWorkspace#1]
Hey @taooceros do you know if this supports VS Code portable version? I got nothing coming up on mine.

**Comment by taooceros** [comment]
Sorry I missed this message. It detects the vscode path via path, so I guess it will not really support portable vscode.

**Comment by KAGEYAM4** [comment]
@taooceros I am using Portable VsCode and added Vscode to path, PowerToysRun is able to detect workspaces but Flow Launcher does not , any idea ?
