### ISSUE TITLE
No documentation?

### ISSUE THREAD

**Issue by Iaotle** [taooceros/Flow.Plugin.VSCodeWorkspace#11]
What's the shortcut for this plugin? There seems to be no readme anywhere in sight.

**Comment by taooceros** [comment]
Sorry for the late response. The default shortcut is `{`.

**Comment by taooceros** [comment]
You can always view the shortcut of a plugin at the plugin setting
![image](https://github.com/taooceros/Flow.Plugin.VSCodeWorkspace/assets/45326534/d770a8b8-c0cb-44ff-9ea9-93364d7b1403)

**Comment by Iaotle** [comment]
@taooceros yeah, but could you add it to the readme as well? Would be good.

**Comment by taooceros** [comment]
Sure
