### ISSUE TITLE
remove old workspaces ?

### ISSUE THREAD

**Issue by katchy3132** [taooceros/Flow.Plugin.VSCodeWorkspace#5]
Is there a way to remove old workspaces ? or maybe a cache?
I removed workspaces from 

> %userprofile%\AppData\Roaming\Code\User\workspaceStorage

but still showing up in the list.

**Comment by deefrawley** [comment]
@katchy3132 @mdroidian how long after you delete a workspace is it still visible? If you delete one, then open Flow and press F5 is it still visible (this reloads all plugins)?

**Comment by taooceros** [comment]
I think we query vscode database, so as long as it has a record, it will be queried

**Comment by mdroidian** [comment]
@deefrawley unfortunately after `F5` it is still visible.  It seems to be still visible indefinitely.  I haven't been able to remove any.

> I think we query vscode database, so as long as it has a record, it will be queried

@taooceros where is this located?

I deleted the `User/globalStorage/storage.json` entry, as well as the `User/workspaceStorage` folder that referenced the workspace in `workspace.json`

I then `F5` refreshed Flow Launcher, but it still showed up 🤷‍♂️

**Comment by taooceros** [comment]
Sorry for the late response. It will be in an entry in sqlite written in json...The path to the sqlite is `{vscodeInstance.AppData}/User/globalStorage/state.vscdb` which in my computer is `%appdata%\Code\User\globalStorage\state.vscdb`, which you can open with any sqlite editor. We query this entry `history.recentlyOpenedPathsList`, which is in json.

If you understand c#, the following line of code might help

https://github.com/taooceros/Flow.Plugin.VSCodeWorkspace/blob/b2eedf3473c34a32b77d0ec04c9eba2d15136652/WorkspacesHelper/VSCodeWorkspacesApi.cs#L102-L123

**Comment by mdroidian** [comment]
Thank you for the response!

With the help of your response, I found a way to remove old workspaces. 🙌

1. Press `ctrl+shift+p` (you may need `command+shift+p` instead if using a Mac) and select `File: Open Recent...`
2. After you click on that, you should see a dropdown with your recently opened projects. Hover with the mouse on the one you want to delete and towards the end of the line you're hovering you should see a small `x` appearing
3. Click on that `x` and you're all done

Source: https://stackoverflow.com/a/74531829/2026619

**Comment by katchy3132** [comment]
I think the approach of @mdroidian where you can remove the results from VSCode itself is good. Thanks!
